import { Router } from "express";
import { createProduct, deleteProduct, getProductById, getProducts, updateProduct } from "../controllers/products.controller";
import { requireAuth } from "../middleware/requireAuth";
import { productImageUpload } from "../middleware/upload";
export const productsRouter = Router();
productsRouter.get("/", (req, res, next) => req.query.all === "true" ? requireAuth(req, res, next) : next(), getProducts);
productsRouter.get("/:id", getProductById);
productsRouter.post("/", requireAuth, productImageUpload, createProduct);
productsRouter.put("/:id", requireAuth, productImageUpload, updateProduct);
productsRouter.delete("/:id", requireAuth, deleteProduct);
