import { Router } from "express";
import { createService, deleteService, getServiceById, getServices, updateService } from "../controllers/services.controller";
import { requireAuth } from "../middleware/requireAuth";
import { serviceImageUpload } from "../middleware/upload";
export const servicesRouter = Router();
servicesRouter.get("/", (req, res, next) => req.query.all === "true" ? requireAuth(req, res, next) : next(), getServices);
servicesRouter.get("/:id", getServiceById);
servicesRouter.post("/", requireAuth, serviceImageUpload, createService);
servicesRouter.put("/:id", requireAuth, serviceImageUpload, updateService);
servicesRouter.delete("/:id", requireAuth, deleteService);
